baseURL = "https://tangentialalmond.cc"
canonifyURLs = false            # Important: prevents Hugo from forcing the placeholder URL
relativeURLs = true             # Best practice for "portable" sites
languageCode = 'en-us'
title = 'Tangential Almond'

[params]
    author = "Amanda Ng"
    daisyTheme = "cupcake"
    hardwareName = "Huawei Mate 20"

[build]
    writeStats = true